"""
Django settings for trainingpr project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k85v_q5%c=4xv_6udqicu4+@qq$kca4-1f+w!_hp@ut^gqw4(y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'nested_admin',
    'tinymce'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trainingpr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trainingpr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'safarnaj_db',
#         'USER': 'safarnaj_safarnaj',
#         'PASSWORD': 'a-5M8f9s0TIo)U',
#         'HOST': 'localhost',
#         'PORT': '5432'
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'az'

TIME_ZONE = 'Asia/Baku'

USE_I18N = True

USE_TZ = True

gettext = lambda s: s
LANGUAGES = (
    ('az', gettext('Azerbaijani')),
    ('en', gettext('English')),
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication'
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1440),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
    'SLIDING_TOKEN_LIFETIME': timedelta(days=30),
    'SLIDING_TOKEN_REFRESH_LIFETIME_LATE_USER': timedelta(days=1),
    'SLIDING_TOKEN_LIFETIME_LATE_USER': timedelta(days=30),
}

CORS_ALLOW_ALL_ORIGINS = True


# MPI / Azericard settings
MPI_PAYMENT_URL = "https://testmpi.3dsecure.az/cgi-bin/cgi_link"
MERCHANT_TERMINAL = "17205084"   # bank tərəfindən verilən terminal
MERCH_NAME = "My Shop"
MERCH_URL = "https://safarnajafov.com"
BACKREF_URL = "https://admin.safarnajafov.com/payments/callback/"
DEFAULT_CURRENCY = "944"   # AZN numeric (use 'AZN' if doc wants alpha, adapt everywhere)

# PEM strings: put real keys into env vars / vault, not plaintext
MERCHANT_PRIVATE_KEY = """-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA33gW6hxicj80XDMxtY81WBXC66juL9uhAXcH1sdHN7qAT1c3
AjfmYIWd6PGhJnVakW8i7LT0r6T08Y0+d9loeVSNp8+EnK8ZUFjjXiuWedc5kQeN
kxis7FLej8Id4Ud7n2dAprOEGRWnKDEfMlgFrkW/GT87jEQQTrDOarlek0OVB/wf
7sYttJUZVx414X/ImUXLOny3lpKY3L/8skJBonadDFdaQiNLYxeecznpjesrmsM5
lEN4AaInBPtf8D3TDhxgGZ2rB2dTSMiaO8KfKEw0rqrSKrwx0Jg7yyTnBYCxEWR7
Ome+5LH/ZsS9yCywAL2n3R/mhLWcahccHMa1HQIDAQABAoIBAEe5SQ2B570IeTtA
eStvV+06KtItaal1ohMQy7TNSBfkZatRcEfnfisrp5es+g6YauWz2G9F0yUO2kkv
DsYzwtryXvbl3YfWkVbe+LbwYX8gq4rXdEKqkFHXdTSJ1sJICa8LWk5G3taYQwrc
3UjwxH3/R8sIJwopjFxdVhsd/PNhi4N0mKp7dw+sk4JwLKh7DS3zxnu+OlSYyoYB
XOVE28PeEDhVgjFEVtdyD8/tLQpZJFfvVeMpZaSEFgNVguksUA6fTNFpGB6muL7q
zjz/wLIxKO7WkcNSn8tq2yDWL1ubjQqdTpngIWXJhzPmhDdDvs5b6Qx//I6eVpm4
D/IBxBcCgYEA6t307arKOnxGHPazpHJAtHd/Anz2PuqHUPa93bGz8d+374H9h28O
I9qYnVyAOl0bG9ujwvPFyEKmMxLH4OSn5/10tVGDaRAjg22uz2vfoDuNoGAvNrSQ
cl8wnjuLI/bcjuoCrNJ1ZmSmzvP+1BPsFl37yi+1ktwt1zlHoHJorG8CgYEA85OW
Yv03ojMJe+xQULEZK/YxzlnHjudQFdA2W6b0J1uptpJ6XGohTio3+WQeGOjGABHv
TQWsQl1pILwEk3otEqNfMU/Em4gTydkZG9oBrmlgxhiV+TATjS2rCIZjzT8UrZno
e3GYVFndpb4CIxpO8sJJ0tD7ryq5sOCfj07M1TMCgYAMeKzA0gjbAi5W62KuoMJ+
0rmT0D7jKGD3E6MRWpZLia2isixcPLFrhfgEoxzL/JWr7QXNHFSsRZ29qImkj3+6
+eJwnlt0AL9iAzj9GqVNRNxIX9Mh/ISPDi7uuAqzZjBgBl0OAD7rqPySkLI/YK9w
oJz2J4JkwfxNKWV8R5b3UQKBgQCKdYz5PEPRuf1cKlsFY4aRjOOHD1X3D9pga/la
ZC9J6DszA1T3D4VbL3ieFaFeO4PCKm/DcsQW/Y5zAy3+v2a7v46vM07pspK9HOG/
CVAHWvOd5//opMGYcStWLz6wP3l7rY+QDGSxHlx2iOoiFiRmrrbUVeOcEUd5GlbZ
WcvqLQKBgQCRR7mZYJhXoHyA7THRiuKQTW3ZZueI+vEo/K/aPD7dfcHlk50A5eZd
52YgdQC9Kr6oji03boiiuNjBnXQaBAPgQRtHtTWWw2Deix5RdVd2+JR24hf8bTI6
5IXTBPAybMPU9VBQsvA7JI+Ku27LEOPHgVxwiuW0qtfBCAPuzySSEw==
-----END RSA PRIVATE KEY-----"""

MPI_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr6qI1IxeWEPxsziZ0WI4
AJw3qQr4jbZNBAhLNdfkogKdBpIAuCXra6enqeWDTa8WPrjkO5Gg0XgzshORVKbC
VRLXkdveY5elHdcOzSNtth+JzCnmx9tovHEgzLsGJZNNmizf8EW6uezhHVxx0qE3
Zcf6xrzmexibJKeUF/+Nt2KdqkOUE1esEfW/ttKDb7w6dTWDS4ticRO83fJmWxxO
iiipsg4DPm3DkcIua0A4ARyTADCqJwoNcB+MjcX50XukSoECgDEeoSn7X7IZeJUt
OS9AWlT/9Lf1dNl0+Ex4u+MU+Jd30qAkEGuJ+EHcaZ/NSD/nNlC0LSjcdTiGFUX7
BwIDAQAB
-----END PUBLIC KEY-----"""
